### ISSUE TITLE
Emotie effect bepalen

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#193]

**Comment by MoeskopsRalph** [comment]
[Emotie effect bepalen.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/5995553/Emotie.effect.bepalen.docx)

**Comment by GOjayson** [comment]
Code geschreven voor de bepaling welk effecten er kunnen afgespeeld worden.

[Emoeffect.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6005411/Emoeffect.docx)

**Comment by Fre101** [comment]
Dit ticket moet mij eens mondeling toegelicht worden want ik begrijp de koppeling tussen deze twee documenten niet.

**Comment by Fre101** [comment]
ik heb nog steeds mondelinge toelichting nodig. Aan het verslag zelf geraak ik er niet uit.
