### ISSUE TITLE
Veel vragen bij achtergelaten project team 4

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#196]
Oorspronkelijke bedoeling was het opbouwen van de hardware en verder te gaan met het werk waar team 4 geëindigd is. Het probleem is dat er veel onduidelijkheden zijn en de documentatie van team 4 tegenvalt. Olaf en ik (jesse) vrezen ervoor heel het project zelf te moeten uitzoeken. Olaf heeft ondertussen Tom Haels van team 4 gestuurd voor meer info. Maar uit het verleden weten we dat het wel even kan duren eer er antwoord is.

**Comment by Fre101** [comment]
de hulp van Tom was geleverd en heeft wat extra inzicht opgeleverd.
dit project was gekickstart door extra personen hier op in te zetten.
Dit is gelukt.
Er blijven moeilijke onderdelen aan dit project.
