### ISSUE TITLE
MQTT op de RPI 3 Team 4 installeren

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#200]
In dit ticket heb ik na het resetten van de Raspberry pi 3 van Team 4, de installatie van MQTT uitgevoerd. Dit omdat we van plan zijn de data van de beacons/RSSI via MQTT naar team 6 (wij dus) door te sturen. 

De installatie is verwezenlijkt door het volgen van deze tutorial: 
https://www.emqx.io/blog/use-mqtt-with-raspberry-pi

**Comment by Fre101** [comment]
ticket mooi in orde, tutorial vermeld
