### ISSUE TITLE
UART-pin Raspberry uitlezen met een testcode op een ESP. 

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#219]

**Comment by GOjayson** [comment]
https://www.raspberrypi.org/documentation/configuration/uart.md

**Comment by GOjayson** [comment]
We kunnen de de UART uitlezen op de rasberry. W
![Knipsel](https://user-images.githubusercontent.com/61419372/110099713-eb8c9e00-7da1-11eb-8b44-e7c578edcb60.PNG)
e kunnen ook data die we vanaf de raspberry sturen ook ontvangen op de ESP.
