### ISSUE TITLE
Documentatie hoe aansluiten beacons. 

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#221]
[Documentatie_Aansluiten_Beacons.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6216091/Documentatie_Aansluiten_Beacons.docx)

[communication protocol.pdf](https://github.com/11902804/MADDIGITAL-TEAM6/files/6089648/communication.protocol.pdf)

**Comment by Fre101** [comment]
Er is uiteindelijk toch overgegaan naar een andere keuze van verbindingen.
Dit ticket gaat terug naar progress.
Update dit ticket naar de gemaakte keuze.

**Comment by Fre101** [comment]
in orde
