### ISSUE TITLE
FOUT ontdekt aansluitingen beacons

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#227]
[Fout_Ontdekt.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6114273/Fout_Ontdekt.docx)

**Comment by Fre101** [comment]
Goed beschreven hoe de fout is ontdekt en wat het gevolg ervan is.

Indien een regel code of grotere blokken onduidelijk zijn moet je altijd even wat bronnen raadplegen.
