### ISSUE TITLE
Kabels opnieuw strippen

### ISSUE THREAD

**Issue by Jesseeverts** [11902804/MADDIGITAL-TEAM6#230]
Zie ticket: "FOUT ontdekt aansluitingen beacons #227" voor de reden achter het strippen van de kabels.
![159430992_488049815936162_4097521840334859053_n](https://user-images.githubusercontent.com/61419254/110598241-d2109b00-8181-11eb-9db0-cac5690347e3.jpg)
![159141957_765629744066388_720670693034062317_n](https://user-images.githubusercontent.com/61419254/110598244-d3da5e80-8181-11eb-89c2-2e2305af1112.jpg)
![159472222_269228708135989_1372757308827764001_n](https://user-images.githubusercontent.com/61419254/110598253-d5a42200-8181-11eb-9a9a-af1ca1795596.jpg)

**Comment by Fre101** [comment]
Waarom wordt dit opnieuw gedaan?

**Comment by Jesseeverts** [comment]
Zie ticket: "FOUT ontdekt aansluitingen beacons #227" voor de reden achter het strippen van de kabels.

**Comment by Fre101** [comment]
in orde
