### ISSUE TITLE
Nauwkeurigheid van 2 beacons bepalen

### ISSUE THREAD

**Issue by B-Willems** [11902804/MADDIGITAL-TEAM6#240]
[Nauwkeurigheid van 2 beacons bepalen.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6156474/Nauwkeurigheid.van.2.beacons.bepalen.docx)

[Beacon_Script.zip](https://github.com/11902804/MADDIGITAL-TEAM6/files/6156484/Beacon_Script.zip)

**Comment by Fre101** [comment]
in orde
