### ISSUE TITLE
Berekening op RSSI maken voor locatiebepaling (X,Y)[momenteel voor 4/8 zones)

### ISSUE THREAD

**Issue by MoeskopsRalph** [11902804/MADDIGITAL-TEAM6#244]

**Comment by GOjayson** [comment]
Code geschreven zodat er 9 zones zijn.
![Naamloos](https://user-images.githubusercontent.com/61419372/115521876-e02afe80-a28b-11eb-8a2c-9a0468c08c0d.png)

**Comment by Fre101** [comment]
in orde
