### ISSUE TITLE
Aan de hand van stengels coördinaten en persoonslocatie berekeningen uitvoeren voor 1 demo opstelling

### ISSUE THREAD

**Issue by MoeskopsRalph** [11902804/MADDIGITAL-TEAM6#249]
[Berekening maken aan de hand van JSON file en handmatige input voor demo opstelling.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6217349/Berekening.maken.aan.de.hand.van.JSON.file.en.handmatige.input.voor.demo.opstelling.docx)

https://github.com/11902804/MADDIGITAL-TEAM6/blob/main/demo_1_stengel.mp4

**Comment by Fre101** [comment]
duidelijk
