### ISSUE TITLE
Berekeningen voor servomotoren naar PSOC zetten

### ISSUE THREAD

**Issue by B-Willems** [11902804/MADDIGITAL-TEAM6#35]
[Hoekberekening omzetten naar PSoC code.docx](https://github.com/11902804/MADDIGITAL-TEAM6/files/6036888/Hoekberekening.omzetten.naar.PSoC.code.docx)

**Comment by MoeskopsRalph** [comment]
3u

**Comment by Fre101** [comment]
in orde
